import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Tailwind Typography</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <p className="text-3xl font-sans font-bold my-2"> Font 3XL Bold </p>
      <p className="text-2xl font-sans font-bold my-2"> Font 2XL Bold </p>
      <p className="text-xl font-sans font-bold my-2"> Font XL Bold </p>
      <p className="text-xl font-sans my-2"> Font XL Normal </p>
      <p className="text-lg font-sans font-bold my-2"> Font LG Bold </p>
      <p className="text-lg font-sans my-2"> Font LG Normal </p>
      <p className="text-md font-sans font-bold my-2"> Font MD Bold </p>
      <p className="text-md font-sans my-2"> Font MD Normal </p>
      <p className="text-sm font-sans font-bold my-2"> Font sm Bold  </p>
      <p className="text-sm font-sans my-2"> Font sm normal  </p>
    </div>
  );
}
